package org.ultimatehg;

import java.util.Random;
import java.util.UUID;

import org.bukkit.Bukkit;
import org.bukkit.ChatColor;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerMoveEvent;

public class Listeners implements Listener {
	public static final String[] blockList = {"ACACIA_FENCE", "ACACIA_FENCE_GATE", "ACACIA_LEAVES", "ACACIA_LOG", "ACACIA_PLANKS", "ACACIA_PRESSURE_PLATE", "ACACIA_SAPLING", "ACACIA_SLAB", "ACACIA_STAIRS", "ACACIA_TRAPDOOR", "ACACIA_WOOD", "ACTIVATOR_RAIL", "ALLIUM", "ANDESITE", "ANDESITE_SLAB", "ANDESITE_STAIRS", "ANDESITE_WALL", "ANVIL", "AZURE_BLUET", "BAMBOO", "BAMBOO_SAPLING", "BARREL", "BEDROCK", "BEETROOTS", "BELL", "BIRCH_FENCE", "BIRCH_FENCE_GATE", "BIRCH_LEAVES", "BIRCH_LOG", "BIRCH_PLANKS", "BIRCH_PRESSURE_PLATE", "BIRCH_SAPLING", "BIRCH_SLAB", "BIRCH_STAIRS", "BIRCH_TRAPDOOR", "BIRCH_WOOD", "BLACK_BANNER", "BLACK_BED", "BLACK_CARPET", "BLACK_CONCRETE", "BLACK_CONCRETE_POWDER", "BLACK_GLAZED_TERRACOTTA", "BLACK_STAINED_GLASS", "BLACK_STAINED_GLASS_PANE", "BLACK_TERRACOTTA", "BLACK_WOOL", "BLAST_FURNACE", "BLUE_BANNER", "BLUE_BED", "BLUE_CARPET", "BLUE_CONCRETE", "BLUE_CONCRETE_POWDER", "BLUE_GLAZED_TERRACOTTA", "BLUE_ICE", "BLUE_ORCHID", "BLUE_STAINED_GLASS", "BLUE_STAINED_GLASS_PANE", "BLUE_TERRACOTTA", "BLUE_WOOL", "BONE_BLOCK", "BOOKSHELF", "BREWING_STAND", "BRICKS", "BRICK_SLAB", "BRICK_STAIRS", "BRICK_WALL", "BROWN_BANNER", "BROWN_BED", "BROWN_CARPET", "BROWN_CONCRETE", "BROWN_CONCRETE_POWDER", "BROWN_GLAZED_TERRACOTTA", "BROWN_MUSHROOM", "BROWN_MUSHROOM_BLOCK", "BROWN_STAINED_GLASS", "BROWN_STAINED_GLASS_PANE", "BROWN_TERRACOTTA", "BROWN_WOOL", "CACTUS", "CAKE", "CAMPFIRE", "CARROTS", "CARTOGRAPHY_TABLE", "CARVED_PUMPKIN", "CAULDRON", "CHEST", "CHIPPED_ANVIL", "CHISELED_QUARTZ_BLOCK", "CHISELED_SANDSTONE", "CHISELED_STONE_BRICKS", "CLAY", "COAL_BLOCK", "COAL_ORE", "COARSE_DIRT", "COBBLESTONE", "COBBLESTONE_SLAB", "COBBLESTONE_STAIRS", "COBBLESTONE_WALL", "COBWEB", "COCOA", "COMPARATOR", "COMPOSTER", "CORNFLOWER", "CRACKED_STONE_BRICKS", "CRAFTING_TABLE", "CUT_SANDSTONE", "CUT_SANDSTONE_SLAB", "CYAN_BANNER", "CYAN_BED", "CYAN_CARPET", "CYAN_CONCRETE", "CYAN_CONCRETE_POWDER", "CYAN_GLAZED_TERRACOTTA", "CYAN_STAINED_GLASS", "CYAN_STAINED_GLASS_PANE", "CYAN_TERRACOTTA", "CYAN_WOOL", "DAMAGED_ANVIL", "DANDELION", "DARK_OAK_FENCE", "DARK_OAK_FENCE_GATE", "DARK_OAK_LEAVES", "DARK_OAK_LOG", "DARK_OAK_PLANKS", "DARK_OAK_PRESSURE_PLATE", "DARK_OAK_SAPLING", "DARK_OAK_SLAB", "DARK_OAK_STAIRS", "DARK_OAK_TRAPDOOR", "DARK_OAK_WOOD", "DAYLIGHT_DETECTOR", "DEAD_BUSH", "DETECTOR_RAIL", "DIAMOND_BLOCK", "DIAMOND_ORE", "DIORITE", "DIORITE_SLAB", "DIORITE_STAIRS", "DIORITE_WALL", "DIRT", "DISPENSER", "DRIED_KELP_BLOCK", "DROPPER", "EMERALD_BLOCK", "EMERALD_ORE", "ENCHANTING_TABLE", "ENDER_CHEST", "FARMLAND", "FERN", "FLETCHING_TABLE", "FLOWER_POT", "FROSTED_ICE", "FURNACE", "GLASS", "GLASS_PANE", "GLOWSTONE", "GOLD_BLOCK", "GOLD_ORE", "GRANITE", "GRANITE_SLAB", "GRANITE_STAIRS", "GRANITE_WALL", "GRASS", "GRASS_BLOCK", "GRASS_PATH", "GRAVEL", "GRAY_BANNER", "GRAY_BED", "GRAY_CARPET", "GRAY_CONCRETE", "GRAY_CONCRETE_POWDER", "GRAY_GLAZED_TERRACOTTA", "GRAY_STAINED_GLASS", "GRAY_STAINED_GLASS_PANE", "GRAY_TERRACOTTA", "GRAY_WOOL", "GREEN_BANNER", "GREEN_BED", "GREEN_CARPET", "GREEN_CONCRETE", "GREEN_CONCRETE_POWDER", "GREEN_GLAZED_TERRACOTTA", "GREEN_STAINED_GLASS", "GREEN_STAINED_GLASS_PANE", "GREEN_TERRACOTTA", "GREEN_WOOL", "GRINDSTONE", "HAY_BLOCK", "HEAVY_WEIGHTED_PRESSURE_PLATE", "HOPPER", "ICE", "IRON_BARS", "IRON_BLOCK", "IRON_ORE", "IRON_TRAPDOOR", "JACK_O_LANTERN", "JUKEBOX", "JUNGLE_FENCE", "JUNGLE_FENCE_GATE", "JUNGLE_LEAVES", "JUNGLE_LOG", "JUNGLE_PLANKS", "JUNGLE_PRESSURE_PLATE", "JUNGLE_SAPLING", "JUNGLE_SLAB", "JUNGLE_STAIRS", "JUNGLE_TRAPDOOR", "JUNGLE_WOOD", "KELP", "KELP_PLANT", "LADDER", "LANTERN", "LAPIS_BLOCK", "LAPIS_ORE", "LARGE_FERN", "LECTERN", "LEVER", "LIGHT_BLUE_BANNER", "LIGHT_BLUE_BED", "LIGHT_BLUE_CARPET", "LIGHT_BLUE_CONCRETE", "LIGHT_BLUE_CONCRETE_POWDER", "LIGHT_BLUE_GLAZED_TERRACOTTA", "LIGHT_BLUE_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS_PANE", "LIGHT_BLUE_TERRACOTTA", "LIGHT_BLUE_WOOL", "LIGHT_GRAY_BANNER", "LIGHT_GRAY_BED", "LIGHT_GRAY_CARPET", "LIGHT_GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE_POWDER", "LIGHT_GRAY_GLAZED_TERRACOTTA", "LIGHT_GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS_PANE", "LIGHT_GRAY_TERRACOTTA", "LIGHT_GRAY_WOOL", "LIGHT_WEIGHTED_PRESSURE_PLATE", "LILAC", "LILY_OF_THE_VALLEY", "LILY_PAD", "LIME_BANNER", "LIME_BED", "LIME_CARPET", "LIME_CONCRETE", "LIME_CONCRETE_POWDER", "LIME_GLAZED_TERRACOTTA", "LIME_STAINED_GLASS", "LIME_STAINED_GLASS_PANE", "LIME_TERRACOTTA", "LIME_WOOL", "LOOM", "MAGENTA_BANNER", "MAGENTA_BED", "MAGENTA_CARPET", "MAGENTA_CONCRETE", "MAGENTA_CONCRETE_POWDER", "MAGENTA_GLAZED_TERRACOTTA", "MAGENTA_STAINED_GLASS", "MAGENTA_STAINED_GLASS_PANE", "MAGENTA_TERRACOTTA", "MAGENTA_WOOL", "MAGMA_BLOCK", "MELON", "MELON_STEM", "MOSSY_COBBLESTONE", "MOSSY_COBBLESTONE_SLAB", "MOSSY_COBBLESTONE_STAIRS", "MOSSY_COBBLESTONE_WALL", "MOSSY_STONE_BRICKS", "MOSSY_STONE_BRICK_SLAB", "MOSSY_STONE_BRICK_STAIRS", "MOSSY_STONE_BRICK_WALL", "MUSHROOM_STEM", "MYCELIUM", "NETHERRACK", "NETHER_BRICKS", "NETHER_BRICK_FENCE", "NETHER_BRICK_SLAB", "NETHER_BRICK_STAIRS", "NETHER_BRICK_WALL", "NETHER_QUARTZ_ORE", "NETHER_WART", "NETHER_WART_BLOCK", "NOTE_BLOCK", "OAK_FENCE", "OAK_FENCE_GATE", "OAK_LEAVES", "OAK_LOG", "OAK_PLANKS", "OAK_PRESSURE_PLATE", "OAK_SAPLING", "OAK_SLAB", "OAK_STAIRS", "OAK_TRAPDOOR", "OAK_WOOD", "OBSERVER", "OBSIDIAN", "ORANGE_BANNER", "ORANGE_BED", "ORANGE_CARPET", "ORANGE_CONCRETE", "ORANGE_CONCRETE_POWDER", "ORANGE_GLAZED_TERRACOTTA", "ORANGE_STAINED_GLASS", "ORANGE_STAINED_GLASS_PANE", "ORANGE_TERRACOTTA", "ORANGE_TULIP", "ORANGE_WOOL", "OXEYE_DAISY", "PACKED_ICE", "PEONY", "PINK_BANNER", "PINK_BED", "PINK_CARPET", "PINK_CONCRETE", "PINK_CONCRETE_POWDER", "PINK_GLAZED_TERRACOTTA", "PINK_STAINED_GLASS", "PINK_STAINED_GLASS_PANE", "PINK_TERRACOTTA", "PINK_TULIP", "PINK_WOOL", "PISTON", "PODZOL", "POLISHED_ANDESITE", "POLISHED_ANDESITE_SLAB", "POLISHED_ANDESITE_STAIRS", "POLISHED_DIORITE", "POLISHED_DIORITE_SLAB", "POLISHED_DIORITE_STAIRS", "POLISHED_GRANITE", "POLISHED_GRANITE_SLAB", "POLISHED_GRANITE_STAIRS", "POPPY", "POTATOES", "POTTED_ACACIA_SAPLING", "POTTED_ALLIUM", "POTTED_AZURE_BLUET", "POTTED_BAMBOO", "POTTED_BIRCH_SAPLING", "POTTED_BLUE_ORCHID", "POTTED_BROWN_MUSHROOM", "POTTED_CACTUS", "POTTED_CORNFLOWER", "POTTED_DANDELION", "POTTED_DARK_OAK_SAPLING", "POTTED_DEAD_BUSH", "POTTED_FERN", "POTTED_JUNGLE_SAPLING", "POTTED_LILY_OF_THE_VALLEY", "POTTED_OAK_SAPLING", "POTTED_ORANGE_TULIP", "POTTED_OXEYE_DAISY", "POTTED_PINK_TULIP", "POTTED_POPPY", "POTTED_RED_MUSHROOM", "POTTED_RED_TULIP", "POTTED_SPRUCE_SAPLING", "POTTED_WHITE_TULIP", "POWERED_RAIL", "PUMPKIN", "PUMPKIN_STEM", "PURPLE_BANNER", "PURPLE_BED", "PURPLE_CARPET", "PURPLE_CONCRETE", "PURPLE_CONCRETE_POWDER", "PURPLE_GLAZED_TERRACOTTA", "PURPLE_STAINED_GLASS", "PURPLE_STAINED_GLASS_PANE", "PURPLE_TERRACOTTA", "PURPLE_WOOL", "QUARTZ_BLOCK", "QUARTZ_PILLAR", "QUARTZ_SLAB", "QUARTZ_STAIRS", "RAIL", "REDSTONE_BLOCK", "REDSTONE_LAMP", "REDSTONE_ORE", "REDSTONE_TORCH", "REDSTONE_WIRE", "RED_BANNER", "RED_BED", "RED_CARPET", "RED_CONCRETE", "RED_CONCRETE_POWDER", "RED_GLAZED_TERRACOTTA", "RED_MUSHROOM", "RED_MUSHROOM_BLOCK", "RED_NETHER_BRICKS", "RED_NETHER_BRICK_SLAB", "RED_NETHER_BRICK_STAIRS", "RED_NETHER_BRICK_WALL", "RED_STAINED_GLASS", "RED_STAINED_GLASS_PANE", "RED_TERRACOTTA", "RED_TULIP", "RED_WOOL", "REPEATER", "ROSE_BUSH", "SAND", "SANDSTONE", "SANDSTONE_SLAB", "SANDSTONE_STAIRS", "SANDSTONE_WALL", "SCAFFOLDING", "SEAGRASS", "SLIME_BLOCK", "SMITHING_TABLE", "SMOKER", "SMOOTH_QUARTZ", "SMOOTH_QUARTZ_SLAB", "SMOOTH_QUARTZ_STAIRS", "SMOOTH_SANDSTONE", "SMOOTH_SANDSTONE_SLAB", "SMOOTH_SANDSTONE_STAIRS", "SMOOTH_STONE", "SMOOTH_STONE_SLAB", "SNOW", "SNOW_BLOCK", "SOUL_SAND", "SPRUCE_FENCE", "SPRUCE_FENCE_GATE", "SPRUCE_LEAVES", "SPRUCE_LOG", "SPRUCE_PLANKS", "SPRUCE_PRESSURE_PLATE", "SPRUCE_SAPLING", "SPRUCE_SLAB", "SPRUCE_STAIRS", "SPRUCE_TRAPDOOR", "SPRUCE_WOOD", "STICKY_PISTON", "STONE", "STONECUTTER", "STONE_BRICKS", "STONE_BRICK_SLAB", "STONE_BRICK_STAIRS", "STONE_BRICK_WALL", "STONE_PRESSURE_PLATE", "STONE_SLAB", "STONE_STAIRS", "STRIPPED_ACACIA_LOG", "STRIPPED_ACACIA_WOOD", "STRIPPED_BIRCH_LOG", "STRIPPED_BIRCH_WOOD", "STRIPPED_DARK_OAK_LOG", "STRIPPED_DARK_OAK_WOOD", "STRIPPED_JUNGLE_LOG", "STRIPPED_JUNGLE_WOOD", "STRIPPED_OAK_LOG", "STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_LOG", "STRIPPED_SPRUCE_WOOD", "SUGAR_CANE", "SUNFLOWER", "SWEET_BERRY_BUSH", "TALL_GRASS", "TALL_SEAGRASS", "TERRACOTTA", "TNT", "TORCH", "TRAPPED_CHEST", "TRIPWIRE", "TRIPWIRE_HOOK", "TURTLE_EGG", "VINE", "WATER", "WHEAT", "WHITE_BANNER", "WHITE_BED", "WHITE_CARPET", "WHITE_CONCRETE", "WHITE_CONCRETE_POWDER", "WHITE_GLAZED_TERRACOTTA", "WHITE_STAINED_GLASS", "WHITE_STAINED_GLASS_PANE", "WHITE_TERRACOTTA", "WHITE_TULIP", "WHITE_WOOL", "YELLOW_BANNER", "YELLOW_BED", "YELLOW_CARPET", "YELLOW_CONCRETE", "YELLOW_CONCRETE_POWDER", "YELLOW_GLAZED_TERRACOTTA", "YELLOW_STAINED_GLASS", "YELLOW_STAINED_GLASS_PANE", "YELLOW_TERRACOTTA", "YELLOW_WOOL"};
	
	private Material block1, block2;
	blockswitch main;
	
	private UUID player1 = null, player2 = null;
	
	private boolean p1step = false, p2step = false;
	
	private BSCountdownTimer countdown = new BSCountdownTimer(this, 600);
	
	public Listeners(Material b1, Material b2, UUID player1, UUID player2, blockswitch main) {
		this.block1 = b1;
		this.block2 = b2;
		this.main = main;
		this.player1 = player1;
		this.player2 = player2;
		countdown.scheduleTimer();
	}
	
	public void endSequence() {
		
		//FOR 2 PLAYERS ONLY
		
		if(p1step && !p2step) {
			main.printChat(ChatColor.RED+""+ChatColor.BOLD+Bukkit.getPlayer(player2).getName()+" has failed to step the designated block");
			main.printChat(ChatColor.GREEN+""+ChatColor.BOLD+Bukkit.getPlayer(player1).getName()+" has won the challenge");
		}
		if(!p1step && p2step) {
			main.printChat(ChatColor.RED+""+ChatColor.BOLD+Bukkit.getPlayer(player1).getName()+" has failed to step the designated block");
			main.printChat(ChatColor.GREEN+""+ChatColor.BOLD+Bukkit.getPlayer(player2).getName()+" has won the challenge");
		}
		if(!p1step && !p2step) {
			main.printChat(ChatColor.RED+""+ChatColor.BOLD+"Both players failed to step the designated block");
			main.printChat(ChatColor.GREEN+""+ChatColor.BOLD+"The game ends in a tie");
		}
		
	}
	
	@EventHandler
	public void onPlayerMove(PlayerMoveEvent e) {
		Player p = e.getPlayer();
		Block block = p.getLocation().getBlock().getRelative(BlockFace.DOWN);
		
		if(p.getName().equals(Bukkit.getPlayer(player1).getName()) && !p1step) {
			if (block.getType() == block1) {
				main.printChat(ChatColor.DARK_GREEN+""+ChatColor.BOLD+Bukkit.getPlayer(player1).getName()+" has successfully stepped on "+block1.toString().replace('_', ' '));
				p1step = true;
			}
		}
		
		if(p.getName().equals(Bukkit.getPlayer(player2).getName()) && !p2step) {
			if (block.getType() == block2) {
				main.printChat(ChatColor.DARK_GREEN+""+ChatColor.BOLD+Bukkit.getPlayer(player2).getName()+" has successfully stepped on "+block2.toString().replace('_', ' '));
				p2step = true;
			}
		}
		
		if(p1step && p2step) {
			p1step = false;
			p2step = false;
			countdown.stopTimer();
			
			Material material1 = null;
			Material material2 = null;
			String selectedMat = null;
			Random random = new Random();
			
			selectedMat = Listeners.blockList[random.nextInt(Listeners.blockList.length)];
			material1 = Material.getMaterial(selectedMat);
			
			selectedMat = Listeners.blockList[random.nextInt(Listeners.blockList.length)];
			material2 = Material.getMaterial(selectedMat);
			
			block1 = material1;
			block2 = material2;
			
			main.printChat(ChatColor.GREEN+Bukkit.getPlayer(player1).getName()+" step on "+block1.toString().replace('_', ' '));
			main.printChat(ChatColor.GREEN+Bukkit.getPlayer(player2).getName()+" step on "+block2.toString().replace('_', ' '));
			countdown.scheduleTimer();
		}
	}
	
}
